custom_logo: 'logo_vectorQC_small.png'
custom_logo_url: 'https://github.com/biocorecrg/vectorQC'
custom_logo_title: 'Vector QC'

read_count_multiplier: 0.001
read_count_prefix: 'K'
read_count_desc: 'thousands'

extra_fn_clean_trim: 
   - '-trimmed'

extra_fn_clean_exts:
    - type: remove
      pattern: _read
    - type: remove
      pattern: -trimmed-pair

table_columns_visible:
    FastQC:
        percent_duplicates: False

module_order:
 - fastqc:
        name: 'FastQC (raw)'
        info: 'This section of the report shows FastQC results on raw reads.'
        path_filters:
            - '*raw_fastqc.zip'
 - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter removal and quality trimming.'
        path_filters:
            - '*filt_fastqc.zip'
 - skewer
  
